Removed unrelated commands in Word and Excel add-ins.
OfficeDev/Office-Samples pull request #110
Opened 2024-09-13 10:38 UTC by richard6094

Removed unrelated Mailbox commands in Word and Excel sample add-ins.

2024-09-19 06:04 UTC, hermanwenhe approved these changes

2024-09-19 15:42 UTC, AlexJerabek requested changes
These changes look good, but we also need to update the readme files. They still reference the commands folder.

2024-09-20 08:01 UTC, richard6094 commented
> These changes look good, but we also need to update the readme files. They still reference the commands folder.

Hi @AlexJerabek, please have a look on the latest commit.

2024-09-23 17:40 UTC, AlexJerabek approved these changes

2024-09-23 17:40 UTC, merged