Copy edit pass on the Excel chart sample readme
OfficeDev/Office-Samples pull request #85
Opened 2024-08-05 21:08 UTC by AlexJerabek

This PR attempts to apply the MSFT style guide and other conventions to the Excel chart sample readme file. I'll use any feedback on this pass when working on other readmes.

2024-08-08 07:04 UTC, MingjiaLiu1995 requested changes

2024-08-08 07:04 UTC, MingjiaLiu1995 commented on Excel-Add-in-ChartAPI-Anylysis-Data/README.md
> +    Install the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger) extension in Visual Studio Code marketplace. Click the
```suggestion
    Install the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger) extension in Visual Studio Code marketplace. Click the <img src="./assets/Icon_Office_Add-ins_Development_Kit.png" width="30" alt="Office Add-ins Development Kit"/> button in the side panel to open the extension.
```

2024-08-08 07:06 UTC, MingjiaLiu1995 commented
@hermanwenhe Could you review this pr and merge it to main?

2024-08-09 01:59 UTC, hermanwenhe approved these changes

2024-08-09 02:40 UTC, MingjiaLiu1995 commented on Excel-Add-in-ChartAPI-Anylysis-Data/README.md
> +    Install the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger) extension in Visual Studio Code marketplace. Click the
Yes. We believe "Office Add-ins Development Kit" should be the public name, and have changed all in the newest package. 
![image](https://github.com/user-attachments/assets/5cb33066-fb80-4b5f-9399-2b775e94e767)

2024-08-09 08:55 UTC, MingjiaLiu1995 approved these changes

2024-08-09 08:55 UTC, merged