Update RUN_WITH_EXTENSION.md
OfficeDev/Office-Samples pull request #86
Opened 2024-08-07 12:34 UTC by MingjiaLiu1995

Add a section to guide developers to explore sample codes per developer's feedback.

2024-08-07 16:33 UTC, AlexJerabek requested changes
There are also a few typos in line 14. Consider using a spell checker extension for VS Code (I use Code Spell Checker).

2024-08-07 16:33 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +- The `./manifest.xml` file in the root directory of the project defines the settings and capabilities of the add-in.  <br>You can check whether your manifest file is valid by selecting `Validate Man
I don't think the term "tree view" is a well understood UI construct. I'd recommend avoiding it and just referring to options in the extension. Also, UI buttons should be **bold**, not `code`.
```suggestion
- The `./manifest.xml` file in the root directory of the project defines the settings and capabilities of the add-in.  <br>You can check whether your manifest file is valid by selecting **Validate Manifest File** option from the Office Add-ins Development Kit.
```

2024-08-07 16:33 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +* **Explore more add-in samples:** `View Samples` in `Office Add-ins Development Kit` tree view.
```suggestion
* **Explore more add-in samples:** Select **View Samples** in the Office Add-ins Development Kit.
```

2024-08-07 16:33 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
>  * **Engage with the team to learn more about updates:** [Join the Microsoft Office Add-ins community call.](https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call)
Slight style thing but avoid having periods in links.
```suggestion
* **Engage with the team to learn more about updates:** [Join the Microsoft Office Add-ins community call](https://learn.microsoft.com/office/dev/add-ins/overview/office-add-ins-community-call).
```

2024-08-07 16:33 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +To explore an Office add-in project, you can start with the key files listed below:
There should only be one H1 per file. Also, if the sentence before a list is a complete sentence, it should end with a period, not a colon.
```suggestion
## Explore the add-in code
To explore an Office add-in project, you can start with the key files listed below.
```

2024-08-08 10:20 UTC, MingjiaLiu1995 commented
Hi @AlexJerabek, I have updated the .md file according to your edits on the Excel Chart sample. Would you please help give it a final review? Then we will apply this RUN_WITH_EXTENSION.md to all samples. Thanks!

Btw, do you think the file name "RUN_WITH_EXTENSION" makes sense to you?

2024-08-08 18:55 UTC, AlexJerabek approved these changes
Approving with one suggestion.

2024-08-08 18:55 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to end developer tool for building Office Add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-09 02:00 UTC, hermanwenhe approved these changes

2024-08-09 08:53 UTC, merged