Update README.md
OfficeDev/Office-Samples pull request #87
Opened 2024-08-07 13:13 UTC by MingjiaLiu1995

Update README file per developer's feedback from validation

2024-08-07 16:46 UTC, AlexJerabek requested changes

2024-08-07 16:46 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/README.md
> +   Click the <img src="./assets/Icon_Office_Add-ins_Development_Kit.png" width="30"/> button in the side panel to open the extension.
Use the same alt text in this image as the icon in the extension displays.
```suggestion
   Click the <img src="./assets/Icon_Office_Add-ins_Development_Kit.png" width="30" alt="Office Add-in Dev Kit"/> button in the side panel to open the extension.
```

2024-08-07 16:46 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/README.md
> +   * In the `Office Add-ins Development Kit` extension, find the sample in `Sample gallery`, click the "create" button at the top of the sample page.
I think this describes the UI flow better. Also, UI options should be **bold** and we should favor "select" over "click" to support non-mouse inputs.
```suggestion
   * Open the Office Add-ins Development Kit extension. Select **View Samples** and choose a sample from the **Sample Gallery**. Select the **Create** button in the top-right corner of the sample page.
```

2024-08-07 16:46 UTC, AlexJerabek commented on Excel-HelloWorld-TaskPane-JS/README.md
> +   * Clone or download this sample to a folder on your computer, then open the folder in Visual Studio Code.
```suggestion
   * [Clone](https://docs.github.com/repositories/creating-and-managing-repositories/cloning-a-repository) this repository or download this sample to a folder on your computer. Then, open the folder in Visual Studio Code.
```

2024-08-08 06:44 UTC, MingjiaLiu1995 commented on Excel-HelloWorld-TaskPane-JS/README.md
> +   Click the <img src="./assets/Icon_Office_Add-ins_Development_Kit.png" width="30"/> button in the side panel to open the extension.
Add the alt text

2024-08-08 06:51 UTC, MingjiaLiu1995 commented on Excel-HelloWorld-TaskPane-JS/README.md
> +   * In the `Office Add-ins Development Kit` extension, find the sample in `Sample gallery`, click the "create" button at the top of the sample page.
I change the description as below:
Open the Office Add-ins Development Kit extension and view samples in the **Sample gallery**. Select the **Create** button in the top-right corner of the sample page.

The reason is that developers may see this page under different circumstances. For developers that already arrive at sample page in VSC from web link or sample gallery, they only need to create, so we might not emphasize on previous actions like Select View samples and choose a sample; For developers that starts from GitHub, they can still go to download and view samples in the sample gallery.

2024-08-08 10:23 UTC, MingjiaLiu1995 commented
@hermanwenhe This change also needs to be merged after you merge #85 , then we apply the pattern to all samples and add Alex as reviewer for a final review. Thanks!

2024-08-08 17:48 UTC, AlexJerabek approved these changes

2024-08-09 02:00 UTC, hermanwenhe approved these changes

2024-08-09 02:00 UTC, merged