Sample readme final review
OfficeDev/Office-Samples pull request #90
Opened 2024-08-12 02:57 UTC by hermanwenhe

2024-08-12 06:30 UTC, MingjiaLiu1995 reviewed
- Fix typos
- Change host to "Word" in Word samples
- Some comments

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/README.md
> +- Close any open instances of Excel.
```suggestion
- Close any open instances of Word.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/README.md
> +For information on running the sample on Excel on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testin
```suggestion
For information on running the sample on Word on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/RUN_WITH_EXTENSION.md
> +    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Ex
```suggestion
    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Word desktop application launches and opens a new document with the sample add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/README.md
> +    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Ex
```suggestion
    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Word desktop application launches and opens a new document with the sample add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/README.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/RUN_WITH_EXTENSION.md
> +- The `./src/taskpane/taskpane.js` file contains the Office JavaScript API code that facilitates interaction between the task pane and the Excel application.
```suggestion
- The `./src/taskpane/taskpane.js` file contains the Office JavaScript API code that facilitates interaction between the task pane and the Word application.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/RUN_WITH_EXTENSION.md
> +For information on running the sample on Excel on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testin
```suggestion
For information on running the sample on Word on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/README.md
> +    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Ex
```suggestion
    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Word desktop application launches and opens a new document with the sample add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/README.md
> +For information on running the sample on Excel on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testin
```suggestion
For information on running the sample on Word on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/README.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/RUN_WITH_EXTENSION.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office Add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/RUN_WITH_EXTENSION.md
> +    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Ex
```suggestion
    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Word desktop application launches and opens a new document with the sample add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/RUN_WITH_EXTENSION.md
> +- The `./src/taskpane/taskpane.js` file contains the Office JavaScript API code that facilitates interaction between the task pane and the Excel application.
```suggestion
- The `./src/taskpane/taskpane.js` file contains the Office JavaScript API code that facilitates interaction between the task pane and the Word application.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/RUN_WITH_EXTENSION.md
> +For information on running the sample on Excel on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testin
```suggestion
For information on running the sample on Word on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/README.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/README.md
> +    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Ex
```suggestion
    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Word desktop application launches and opens a new document with the sample add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/README.md
> +- Close any open instances of Excel.
```suggestion
- Close any open instances of Word.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/README.md
> +For information on running the sample on Excel on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testin
```suggestion
For information on running the sample on Word on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office Add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Ex
```suggestion
    The extension then checks that the prerequisites are met before debugging starts. Check the terminal for detailed information if there are issues with your environment. After this process, the Word desktop application launches and opens a new document with the sample add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +For information on running the sample on Excel on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testin
```suggestion
For information on running the sample on Word on the web, see [Sideload Office Add-ins to Office on the web](https://learn.microsoft.com/office/dev/add-ins/testing/sideload-office-add-ins-for-testing).
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +- Close any open instances of Excel.
```suggestion
- Close any open instances of Word.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/RUN_WITH_EXTENSION.md
> +- Close any open instances of Excel.
```suggestion
- Close any open instances of Word.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/README.md
> +- Close any open instances of Excel.
```suggestion
- Close any open instances of Word.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-WritingAssistant/RUN_WITH_EXTENSION.md
> +- Close any open instances of Excel.
```suggestion
- Close any open instances of Word.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-HelloWorld-TaskPane-JS/RUN_WITH_EXTENSION.md
> +- The `./src/taskpane/taskpane.js` file contains the Office JavaScript API code that facilitates interaction between the task pane and the Excel application.
```suggestion
- The `./src/taskpane/taskpane.js` file contains the Office JavaScript API code that facilitates interaction between the task pane and the Word application.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Excel-Add-in-Mail-Merge/RUN_WITH_EXTENSION.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office Add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Excel-Add-in-ShapeAPI-Dashboard/README.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Excel-Add-in-ShapeAPI-Dashboard/RUN_WITH_EXTENSION.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office Add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Excel-HelloWorld-TaskPane-JS/README.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on RUN_WITH_EXTENSION.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office Add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 06:30 UTC, MingjiaLiu1995 commented on Word-Add-in-AIGC/RUN_WITH_EXTENSION.md
> +We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Devel
```suggestion
We recommend you try this sample by using the [Office Add-ins Development Kit](https://marketplace.visualstudio.com/items?itemName=msoffice.microsoft-office-add-in-debugger). The Office Add-ins Development Kit is an end-to-end developer tool for building Office Add-ins. It helps create, run, and debug an Office Add-in.
```

2024-08-12 08:53 UTC, hermanwenhe commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
This pixel image is not actually added in all sample task panes. Adding these means extra work and hight maintenance effort, we should carefully discuss the necessity of this.

2024-08-12 08:59 UTC, hermanwenhe commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
I've restored this statement of those actually have this 1-pixel image in the taskpane.html.

2024-08-12 16:51 UTC, AlexJerabek requested changes

2024-08-12 16:51 UTC, AlexJerabek commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
Please work with @davidchesnut here, as he set this up for the main samples repo and shares the data with the broader team.

2024-08-12 16:51 UTC, AlexJerabek commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +    <img src="./assets/devkit_preview.png" width="500" alt="Screenshot shows Preview your Office add-in in Office Add-ins Development Kit"/>
A few issues with this screenshot:
1. The alt text should not describe the image as a "screenshot", but rather what the screenshot is of. It's redundant because the screen reader already describes this as an image. 
```suggestion
    <img src="./assets/devkit_preview.png" width="500" alt="The Office Add-ins Development Kit task pane options to build and test your add-in."/>
```
2. The image has a lot of text. This makes the alt text hard to write because you'd need to include all that text in the alt text (if someone can't see, they still need the information from the image).
3. Additionally, images with text can't be translated. 
4. I find the image's visual flow to be off. Everything is in English, so I'm reading top-to-bottom, left-to-right. The first thing I see is the red box with the menu options, but I think you intend the Dev Kit icon to be the first thing readers see (since they'll need to click there first).
<img width="711" alt="image" src="https://github.com/user-attachments/assets/51fdea94-d65e-4698-9888-81902ff5ee41">

2024-08-12 16:51 UTC, AlexJerabek commented on Excel-Add-in-Mail-Merge/README.md
>  |   |   | commands.js
This sample doesn't have a commands folder. Please double check the file structure for all the samples.

2024-08-12 16:51 UTC, AlexJerabek commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +   You can use either of the ways to download the sample code:
Grammar suggestion, here and elsewhere:
```suggestion
   To download this sample code, either:
```

2024-08-12 16:51 UTC, AlexJerabek commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +    Select **Preview Your Office Add-in(F5)** to launch the add-in and debug the code. In the drop down menu, select the option **Desktop (Edge Chromium)**.
According to the MSFT style guide, we should avoid referring to UI controls by their type (i.e.: "dropdown menu"). https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28800

What is this menu actually called in VS Code?

2024-08-12 16:51 UTC, AlexJerabek commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +|   |   | taskpane.html         Task pane entry html
Outside of variable or file names, use the proper capitalization for terms like HTML.
```suggestion
|   |   | taskpane.html         Task pane entry HTML
```

2024-08-12 16:51 UTC, AlexJerabek commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +|   |   | functions-worker.js   Web worker js
Similar suggestion as above.
```suggestion
|   |   | functions.js          Custom function JavaScript
|   |   | functions-worker.js   Web worker JavaScript
```

2024-08-13 02:07 UTC, hermanwenhe commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
@MingjiaLiu1995 Can you follow up on this? I think the first question mark is whether this is a blocker for public preview.

2024-08-13 02:20 UTC, hermanwenhe commented on Excel-Add-in-Mail-Merge/README.md
>  |   |   | commands.js
Done.

2024-08-13 03:34 UTC, MingjiaLiu1995 commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
@hermanwenhe Can you be more specific on what kind of extra work we need to add the pixel image? It seems the image is already hosted and we need to align the naming principle with David?

2024-08-13 05:33 UTC, MingjiaLiu1995 commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +    <img src="./assets/devkit_preview.png" width="500" alt="Screenshot shows Preview your Office add-in in Office Add-ins Development Kit"/>
I think this image is at stale and should be replaced. I can't find it in the pr files, @hermanwenhe to confirm we have deleted it.

2024-08-13 06:16 UTC, hermanwenhe commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
@MingjiaLiu1995 I might misunderstand something. If your goal is to measure the traffic to GitHub repo, then it can't be achieved. This is because the readme content will be reused in sample gallery so the same 1 pixel image will be loaded in the detail page of sample gallery.

2024-08-13 08:49 UTC, MingjiaLiu1995 commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +    Select **Preview Your Office Add-in(F5)** to launch the add-in and debug the code. In the drop down menu, select the option **Desktop (Edge Chromium)**.
It's called "[Quick Pick](https://code.visualstudio.com/api/ux-guidelines/overview#quick-pick)"

2024-08-13 08:52 UTC, MingjiaLiu1995 commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
Synced offline. We will align the telemetry with other samples to indicate the popularity.

2024-08-14 07:13 UTC, hermanwenhe commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> -<img src="https://pnptelemetry.azurewebsites.net/pnp-officeaddins/samples/word-add-in-aigc">
I will use another PR to address this.

2024-08-14 20:58 UTC, AlexJerabek approved these changes
Approving with one suggested change across the readmes.

2024-08-14 20:58 UTC, AlexJerabek commented on Excel-Add-in-Custom-Function-Using-WebWorker/README.md
> +    Select **Preview Your Office Add-in(F5)** to launch the add-in and debug the code. In the drop down menu, select the option **Desktop (Edge Chromium)**.
The option seems to be called "Edge Desktop (Edge Chromium)", so we should be consistent here. Also, let's use the proper term for the dropdown menu, "Quick Pick".
```suggestion
    Select **Preview Your Office Add-in(F5)** to launch the add-in and debug the code. In the Quick Pick menu, select the option **Edge Desktop (Edge Chromium)**.
```

2024-08-19 03:06 UTC, merged