Run spell check and markdown linter
OfficeDev/Office-Samples pull request #91
Opened 2024-08-15 16:55 UTC by AlexJerabek

This PR is the result of a couple tools to improve spelling and formatting. It is not a detailed editing pass.

2024-08-19 03:10 UTC, hermanwenhe requested changes

2024-08-19 03:10 UTC, hermanwenhe commented on .config/samples-config-v1.json
> +            "id": "Excel-Add-in-ChartAPI-Analysis-Data",
This id is for matching the sample folder under the root directory of this repo. If you change this id you should sync the same change with the folder name of "Excel-Add-in-ChartAPI-Anylysis-Data". Otherwise this sample won't show in sample gallery because of the unmatchable id.

2024-08-19 03:13 UTC, hermanwenhe commented
I just merge the PR approved last week and it shows a lot of merge conflict between this PR and main branch. Conflicts should be resolved or you can publish a new PR based on the latest main branch.

2024-08-19 03:18 UTC, hermanwenhe commented
Another thing is, set the target branch for "dev" for PRs in future. The main branch is release branch, which means the content of this branch would directly used by the Dev Kit. We should merge our PRs to dev branch and merge the dev into main after we make sure it's well tested. The PRs before this were set to merge into main because the Dev Kit was not released yet. Considering we're going public preview this week, we need to start following the right and cautious way to update samples.

2024-08-19 16:27 UTC, AlexJerabek commented
> Another thing is, set the target branch for "dev" for PRs in future. The main branch is release branch, which means the content of this branch would directly used by the Dev Kit. We should merge our PRs to dev branch and merge the dev into main after we make sure it's well tested. The PRs before this were set to merge into main because the Dev Kit was not released yet. Considering we're going public preview this week, we need to start following the right and cautious way to update samples.

Is this process documented anywhere? I didn't see a "CONTRIBUTING.md" file defining expectations of public PRs.

2024-08-19 16:38 UTC, closed without merging

2024-08-20 01:18 UTC, hermanwenhe commented
@AlexJerabek I will add a contributing document. Thanks for reminding.